namespace LibraryManagement.Shared.Domain;

/// <summary>
/// The hook that lets the kernel build a strongly typed identifier from its underlying
/// <see cref="Guid"/> without requiring a public parameterless constructor on the derived type.
/// </summary>
/// <typeparam name="TSelf">The identifier type implementing this interface.</typeparam>
/// <remarks>
/// Implement it explicitly so it does not surface on the public API of the identifier: callers
/// should go through <see cref="EntityId{TEntityId}.Create"/> and
/// <see cref="EntityId{TEntityId}.Generate"/>, which is what keeps the generation strategy owned
/// by this kernel rather than duplicated in every bounded context.
/// </remarks>
public interface IEntityId<TSelf>
    where TSelf : IEntityId<TSelf>
{
    /// <summary>
    /// Builds an instance of <typeparamref name="TSelf"/> wrapping <paramref name="value"/>.
    /// </summary>
    /// <param name="value">The underlying value of the identifier.</param>
    /// <returns>A new instance of <typeparamref name="TSelf"/>.</returns>
    static abstract TSelf FromValue(Guid value);
}

/// <summary>
/// Represents the identifier of an <see cref="Entity"/>. The underlying value is always a
/// <see cref="Guid"/>: an identifier carries no meaning beyond identity, so there is nothing
/// to gain from letting each entity pick its own key type, and plenty to lose in the mapping.
/// </summary>
/// <typeparam name="TEntityId">The concrete identifier type deriving from this class.</typeparam>
/// <remarks>
/// <para>
/// An <see cref="EntityId{TEntityId}"/> has value semantics even though it does not inherit from
/// <see cref="ValueObject"/>: equality over a single <see cref="Guid"/> is cheaper to express
/// directly than through <c>GetEqualityComponents</c>, which would box the value on every
/// comparison.
/// </para>
/// <para>
/// Declare an identifier by deriving from this class and implementing
/// <see cref="IEntityId{TSelf}"/> explicitly. The private constructor is what makes an invalid
/// identifier unrepresentable — there is no way to obtain one that is not backed by a real value:
/// </para>
/// <code>
/// public sealed class BookId : EntityId&lt;BookId&gt;, IEntityId&lt;BookId&gt;
/// {
///     private BookId(Guid value) : base(value) { }
///
///     static BookId IEntityId&lt;BookId&gt;.FromValue(Guid value) => new(value);
/// }
/// </code>
/// <para>
/// Identifiers are generated by the domain, not by the database: <see cref="Generate"/> produces
/// a value before the entity is ever persisted, which is what lets a caller know an entity's
/// identity without waiting for a round trip.
/// </para>
/// </remarks>
public abstract class EntityId<TEntityId> : IEquatable<TEntityId>
    where TEntityId : EntityId<TEntityId>, IEntityId<TEntityId>
{
    /// <summary>
    /// Gets the underlying value of this identifier. Never <see cref="Guid.Empty"/>.
    /// </summary>
    public Guid Value { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="EntityId{TEntityId}"/> class.
    /// </summary>
    /// <param name="value">The underlying value of the identifier.</param>
    /// <exception cref="ArgumentException">
    /// Thrown when <paramref name="value"/> is <see cref="Guid.Empty"/>.
    /// </exception>
    protected EntityId(Guid value)
    {
        if (value == Guid.Empty)
        {
            throw new ArgumentException("An entity id cannot be the empty GUID.", nameof(value));
        }

        Value = value;
    }

    /// <summary>
    /// Creates an identifier wrapping an existing <paramref name="value"/>. Use this when the
    /// value comes from outside the domain — a request, a message, or the database.
    /// </summary>
    /// <param name="value">The underlying value of the identifier.</param>
    /// <returns>A new instance of <typeparamref name="TEntityId"/>.</returns>
    /// <exception cref="ArgumentException">
    /// Thrown when <paramref name="value"/> is <see cref="Guid.Empty"/>.
    /// </exception>
    public static TEntityId Create(Guid value) => TEntityId.FromValue(value);

    /// <summary>
    /// Generates a brand new identifier. The value is a version 7 UUID: its leading 48 bits are
    /// the creation timestamp in milliseconds, so freshly generated identifiers stay clustered at
    /// the end of an index instead of scattering writes across it the way a random version 4 UUID
    /// does.
    /// </summary>
    /// <returns>A new instance of <typeparamref name="TEntityId"/>.</returns>
    /// <remarks>
    /// <para>
    /// Ordering holds across milliseconds only. Within a single millisecond the remaining bits are
    /// random — RFC 9562 leaves the monotonic counter optional and .NET does not implement one —
    /// so identifiers created in the same millisecond do not sort in creation order. Do not use an
    /// identifier as a chronological sort key; use an explicit timestamp for that.
    /// </para>
    /// <para>
    /// A version 7 UUID discloses its creation time to anyone who sees it, for instance in a URL
    /// or an API payload. That is an accepted trade-off here; reconsider it for identifiers that
    /// end up in front of untrusted parties and whose creation time is sensitive.
    /// </para>
    /// </remarks>
    public static TEntityId Generate() => TEntityId.FromValue(Guid.CreateVersion7());

    /// <summary>
    /// Determines whether this identifier and <paramref name="other"/> are of the same concrete
    /// type and carry the same value.
    /// </summary>
    /// <param name="other">The identifier to compare with this one.</param>
    /// <returns>
    /// <see langword="true"/> if both identifiers are equal; <see langword="false"/> otherwise.
    /// </returns>
    public bool Equals(TEntityId? other)
    {
        if (other is null)
        {
            return false;
        }

        if (ReferenceEquals(this, other))
        {
            return true;
        }

        if (GetType() != other.GetType())
        {
            return false;
        }

        return Value.Equals(other.Value);
    }

    /// <inheritdoc/>
    public sealed override bool Equals(object? obj)
    {
        return obj is TEntityId other && Equals(other);
    }

    /// <inheritdoc/>
    public sealed override int GetHashCode()
    {
        return Value.GetHashCode();
    }

    /// <summary>
    /// Returns the underlying value of this identifier.
    /// </summary>
    public override string ToString() => Value.ToString();

    /// <summary>
    /// Determines whether two identifiers are equal.
    /// </summary>
    public static bool operator ==(EntityId<TEntityId>? left, EntityId<TEntityId>? right)
    {
        return Equals(left, right);
    }

    /// <summary>
    /// Determines whether two identifiers are different.
    /// </summary>
    public static bool operator !=(EntityId<TEntityId>? left, EntityId<TEntityId>? right)
    {
        return !Equals(left, right);
    }
}
