using System.Diagnostics.CodeAnalysis;

namespace LibraryManagement.Shared.Domain;

/// <summary>
/// Represents an abstract entity with a unique identifier and audit properties.
/// </summary>
/// <typeparam name="TEntityId">The type of the unique identifier for the entity.</typeparam>
public abstract class Entity<TEntityId> : Entity, IAuditable
    where TEntityId : EntityId<TEntityId>, IEntityId<TEntityId>
{
    /// <summary>
    /// Gets the unique identifier for the entity. Assigned once, at construction, and never again.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The setter is private rather than <see langword="init"/> on purpose: an <c>init</c> accessor
    /// is reachable from an object initializer, so <c>new Book(id) { Id = somethingElse }</c> would
    /// compile and silently win over the constructor — defeating the closed construction that
    /// <see cref="EntityId{TEntityId}"/> goes to some length to guarantee.
    /// </para>
    /// <para>
    /// No initializer is needed: the sole constructor assigns it, so nullability analysis is
    /// satisfied and no identifier is ever generated only to be discarded. The persistence layer
    /// writes it back on materialization through the private setter or the compiler-generated
    /// backing field, both of which it reaches by reflection.
    /// </para>
    /// </remarks>
    public TEntityId Id { get; private set; }

    /// <summary>
    /// Gets the date and time at which the entity was created.
    /// </summary>
    public DateTimeOffset CreatedOn { get; }

    /// <inheritdoc cref="IAuditable.CreatedBy"/>
    public string? CreatedBy { get; }

    /// <summary>
    /// Gets the date and time at which the entity was last modified, if any.
    /// </summary>
    public DateTimeOffset? ModifiedOn { get; }

    /// <summary>
    /// Gets the identifier of the user who last modified the entity, if any.
    /// </summary>
    public string? ModifiedBy { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="Entity{TEntityId}"/> class with the identity
    /// it will keep for its whole lifetime.
    /// </summary>
    /// <param name="id">The identifier of the entity.</param>
    /// <remarks>
    /// <para>
    /// The identifier is required at construction rather than assigned on save: it is an invariant
    /// of the entity, and it is generated by the domain through
    /// <see cref="EntityId{TEntityId}.Generate"/>. That is what lets a caller know an entity's
    /// identity without waiting for a database round trip — which matters here, since commands
    /// return no value and the caller has nothing else to go on.
    /// </para>
    /// <para>
    /// This is the only constructor of the hierarchy, so every concrete entity must supply an
    /// identifier. Constructors are not inherited: a concrete entity that needs a parameterless
    /// constructor — for a persistence framework that insists on one — has to declare its own.
    /// </para>
    /// </remarks>
    protected Entity(TEntityId id) => Id = id;

    /// <summary>
    /// Determines whether this entity and <paramref name="other"/> share the same identity.
    /// Entities are compared by <see cref="Id"/> alone, never by their attributes: that is what
    /// distinguishes an entity from a <see cref="ValueObject"/>.
    /// </summary>
    /// <param name="other">The entity to compare with this one.</param>
    /// <returns>
    /// <see langword="true"/> if both entities have the same identifier;
    /// <see langword="false"/> otherwise.
    /// </returns>
    protected bool Equals(Entity<TEntityId> other)
    {
        return Id.Equals(other.Id);
    }

    /// <inheritdoc/>
    public override bool Equals(object? obj)
    {
        if (obj is null)
        {
            return false;
        }

        if (ReferenceEquals(this, obj))
        {
            return true;
        }

        if (obj.GetType() != this.GetType())
        {
            return false;
        }

        return Equals((Entity<TEntityId>)obj);
    }

    /// <inheritdoc/>
    /// <remarks>
    /// Hashes on <see cref="Id"/> alone, to stay consistent with <see cref="Equals(object?)"/>.
    /// Anything else — a flag saying whether the entity has been persisted, for instance — would
    /// give two equal entities different hash codes, and would change an entity's hash code partway
    /// through its life, losing it from any hash-based collection it had been placed in beforehand.
    /// </remarks>
    public override int GetHashCode()
    {
        return Id.GetHashCode();
    }

    /// <summary>
    /// Determines whether two entities share the same identity.
    /// </summary>
    public static bool operator ==(Entity<TEntityId>? a, Entity<TEntityId>? b)
    {
        if (a is null && b is null)
        {
            return true;
        }

        if (a is null || b is null)
        {
            return false;
        }

        return a.Equals(b);
    }

    /// <summary>
    /// Determines whether two entities have different identities.
    /// </summary>
    public static bool operator !=(Entity<TEntityId>? a, Entity<TEntityId>? b)
    {
        return !(a == b);
    }
}

/// <summary>
/// Marker class for entities, letting infrastructure discover them without knowing their
/// identifier type. Mirrors the <see cref="ValueObject"/> / <see cref="ValueObject{TSelf}"/>
/// pairing: the non-generic type is the marker, the generic one carries the behavior.
/// </summary>
[SuppressMessage(
    "Minor Code Smell",
    "S2094:Classes should not be empty",
    Justification = "Deliberate marker type, mirroring the ValueObject / ValueObject<TSelf> pairing.")]
public abstract class Entity
{
}

/// <summary>
/// Represents an <see cref="Entity"/> that is auditable.
/// </summary>
public interface IAuditable
{
    /// <summary>
    /// Gets the date and time at which the entity was created.
    /// </summary>
    public DateTimeOffset CreatedOn { get; }

    /// <summary>
    /// Gets the identifier of the user who created the entity, or <see langword="null"/> when the
    /// creation is attributable to no one.
    /// </summary>
    /// <remarks>
    /// Nullable for the same reason <see cref="ModifiedBy"/> is. A migration, a seeding script or a
    /// nightly job acts on nobody's behalf, and so does every command until Staff Access exists. An
    /// empty string in its place would be a value someone invented, and a column of invented values
    /// reads, at a glance, exactly like a column of real ones.
    /// </remarks>
    public string? CreatedBy { get; }

    /// <summary>
    /// Gets the date and time at which the entity was last modified, if any.
    /// </summary>
    public DateTimeOffset? ModifiedOn { get; }

    /// <summary>
    /// Gets the identifier of the user who last modified the entity, if any.
    /// </summary>
    public string? ModifiedBy { get; }
}

/// <summary>
/// Represents an object that has a collection of <see cref="IDomainEvent"/>.
/// Usually the <see cref="IAggregateRoot"/> are the only model having <see cref="IDomainEvent"/>.
/// </summary>
public interface IHasDomainEvents
{
    /// <summary>
    /// Gets the domain events raised by this aggregate root.
    /// </summary>
    public IReadOnlyList<IDomainEvent> DomainEvents { get; }

    /// <summary>
    /// Clears the domain events raised by the aggregate root.
    /// </summary>
    public void ClearDomainEvents();
}
