// <auto-generated />
using System;
using LibraryManagement.Charges.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.Charges.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(ChargesDbContext))]
    [Migration("20260809184006_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("charges")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagement.Charges.Domain.Accounts.Charge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CopyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("IncurredOn")
                        .HasColumnType("date");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Paid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CopyId")
                        .HasFilter("[Kind] = N'ReplacementCharge'");

                    b.HasIndex("MemberId");

                    b.ToTable("Charge", "charges");

                    b.HasDiscriminator<string>("Kind").HasValue("Charge");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LibraryManagement.Charges.Domain.Accounts.MemberAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("MemberAccount", "charges");
                });

            modelBuilder.Entity("LibraryManagement.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeadOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateTimeOffset>("StoredOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_OutboxMessage_Pending")
                        .HasFilter("[ProcessedOn] IS NULL AND [DeadOn] IS NULL");

                    b.ToTable("OutboxMessage", "charges");
                });

            modelBuilder.Entity("LibraryManagement.Charges.Domain.Accounts.DamageCharge", b =>
                {
                    b.HasBaseType("LibraryManagement.Charges.Domain.Accounts.Charge");

                    b.HasDiscriminator().HasValue("DamageCharge");
                });

            modelBuilder.Entity("LibraryManagement.Charges.Domain.Accounts.OverdueFine", b =>
                {
                    b.HasBaseType("LibraryManagement.Charges.Domain.Accounts.Charge");

                    b.Property<int>("DaysLate")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("OverdueFine");
                });

            modelBuilder.Entity("LibraryManagement.Charges.Domain.Accounts.ReplacementCharge", b =>
                {
                    b.HasBaseType("LibraryManagement.Charges.Domain.Accounts.Charge");

                    b.HasDiscriminator().HasValue("ReplacementCharge");
                });

            modelBuilder.Entity("LibraryManagement.Charges.Domain.Accounts.Charge", b =>
                {
                    b.HasOne("LibraryManagement.Charges.Domain.Accounts.MemberAccount", null)
                        .WithMany("Charges")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LibraryManagement.Charges.Domain.Accounts.MemberAccount", b =>
                {
                    b.OwnsMany("LibraryManagement.Charges.Domain.Accounts.PricedLoan", "PricedLoans", b1 =>
                        {
                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("LoanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Kind")
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)");

                            b1.HasKey("MemberId", "LoanId", "Kind");

                            b1.ToTable("PricedLoan", "charges");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.Navigation("PricedLoans");
                });

            modelBuilder.Entity("LibraryManagement.Charges.Domain.Accounts.MemberAccount", b =>
                {
                    b.Navigation("Charges");
                });
#pragma warning restore 612, 618
        }
    }
}
