// <auto-generated />
using System;
using System.Collections.Generic;
using LibraryManagement.Members.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.Members.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(MembersDbContext))]
    partial class MembersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("members")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagement.Members.Domain.Members.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ErasedOn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("MembershipEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("MembershipStart")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ContactDetails", "LibraryManagement.Members.Domain.Members.Member.ContactDetails#ContactDetails", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Email")
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)")
                                .HasColumnName("Email");

                            b1.Property<string>("Phone")
                                .HasMaxLength(32)
                                .HasColumnType("nvarchar(32)")
                                .HasColumnName("Phone");

                            b1.Property<string>("PostalAddress")
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("PostalAddress");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Guardian", "LibraryManagement.Members.Domain.Members.Member.Guardian#Guardian", b1 =>
                        {
                            b1.Property<bool>("Present")
                                .HasColumnType("bit");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Contact", "LibraryManagement.Members.Domain.Members.Member.Guardian#Guardian.Contact#ContactDetails", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Email")
                                        .HasMaxLength(254)
                                        .HasColumnType("nvarchar(254)")
                                        .HasColumnName("GuardianEmail");

                                    b2.Property<string>("Phone")
                                        .HasMaxLength(32)
                                        .HasColumnType("nvarchar(32)")
                                        .HasColumnName("GuardianPhone");

                                    b2.Property<string>("PostalAddress")
                                        .HasMaxLength(256)
                                        .HasColumnType("nvarchar(256)")
                                        .HasColumnName("GuardianPostalAddress");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Name", "LibraryManagement.Members.Domain.Members.Member.Guardian#Guardian.Name#MemberName", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("FamilyName")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("nvarchar(64)")
                                        .HasColumnName("GuardianFamilyName");

                                    b2.Property<string>("GivenName")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("nvarchar(64)")
                                        .HasColumnName("GuardianGivenName");
                                });

                            b1.HasDiscriminator<bool>("Present").HasValue(true);
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "LibraryManagement.Members.Domain.Members.Member.Name#MemberName", b1 =>
                        {
                            b1.Property<string>("FamilyName")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("FamilyName");

                            b1.Property<string>("GivenName")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)")
                                .HasColumnName("GivenName");

                            b1.Property<bool>("Present")
                                .HasColumnType("bit");

                            b1.HasDiscriminator<bool>("Present").HasValue(true);
                        });

                    b.HasKey("Id");

                    b.HasIndex("CardNumber")
                        .IsUnique()
                        .HasFilter("[CardNumber] IS NOT NULL");

                    b.ToTable("Member", "members");
                });

            modelBuilder.Entity("LibraryManagement.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeadOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateTimeOffset>("StoredOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_OutboxMessage_Pending")
                        .HasFilter("[ProcessedOn] IS NULL AND [DeadOn] IS NULL");

                    b.ToTable("OutboxMessage", "members");
                });
#pragma warning restore 612, 618
        }
    }
}
