// <auto-generated />
using System;
using System.Collections.Generic;
using LibraryManagement.Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.Catalog.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260809183952_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagement.Catalog.Domain.Authors.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("PreferredName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "LifeYears", "LibraryManagement.Catalog.Domain.Authors.Author.LifeYears#LifeYears", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int?>("Birth")
                                .HasColumnType("int")
                                .HasColumnName("BirthYear");

                            b1.Property<int?>("Death")
                                .HasColumnType("int")
                                .HasColumnName("DeathYear");
                        });

                    b.HasKey("Id");

                    b.HasIndex("PreferredName");

                    b.ToTable("Author", "catalog");
                });

            modelBuilder.Entity("LibraryManagement.Catalog.Domain.Editions.Edition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("Isbn")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Isbn");

                    b.HasIndex("WorkId");

                    b.ToTable("Edition", "catalog");
                });

            modelBuilder.Entity("LibraryManagement.Catalog.Domain.Works.Work", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("PreferredTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("PreferredTitle");

                    b.ToTable("Work", "catalog");
                });

            modelBuilder.Entity("LibraryManagement.Catalog.Infrastructure.Search.AccessPoint", b =>
                {
                    b.Property<string>("Kind")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Form")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("bit");

                    b.HasKey("Kind", "TargetId", "Form");

                    b.HasIndex("Form");

                    b.ToTable("AccessPoint", "catalog");
                });

            modelBuilder.Entity("LibraryManagement.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeadOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateTimeOffset>("StoredOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_OutboxMessage_Pending")
                        .HasFilter("[ProcessedOn] IS NULL AND [DeadOn] IS NULL");

                    b.ToTable("OutboxMessage", "catalog");
                });

            modelBuilder.Entity("LibraryManagement.Catalog.Domain.Authors.Author", b =>
                {
                    b.OwnsMany("LibraryManagement.Catalog.Domain.Authors.NameForm", "VariantNames", b1 =>
                        {
                            b1.Property<Guid>("AuthorId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Name");

                            b1.HasKey("AuthorId", "Value");

                            b1.HasIndex("Value");

                            b1.ToTable("AuthorVariantName", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("AuthorId");
                        });

                    b.Navigation("VariantNames");
                });

            modelBuilder.Entity("LibraryManagement.Catalog.Domain.Works.Work", b =>
                {
                    b.OwnsMany("LibraryManagement.Catalog.Domain.Authors.AuthorId", "AuthorIds", b1 =>
                        {
                            b1.Property<Guid>("WorkId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("AuthorId");

                            b1.HasKey("WorkId", "Value");

                            b1.HasIndex("Value");

                            b1.ToTable("WorkAuthor", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("WorkId");
                        });

                    b.Navigation("AuthorIds");
                });
#pragma warning restore 612, 618
        }
    }
}
