// <auto-generated />
using System;
using LibraryManagement.Circulation.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.Circulation.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(CirculationDbContext))]
    partial class CirculationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("circulation")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagement.Circulation.Domain.Holds.HoldQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("HoldQueue", "circulation");
                });

            modelBuilder.Entity("LibraryManagement.Circulation.Domain.Loans.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BorrowerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("CheckedOutOn")
                        .HasColumnType("date");

                    b.Property<Guid>("CopyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateOnly?>("DeclaredLostOn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateOnly?>("RecoveredOn")
                        .HasColumnType("date");

                    b.Property<int>("RenewalCount")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ReturnedOn")
                        .HasColumnType("date");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("BorrowerId");

                    b.HasIndex("CopyId")
                        .IsUnique()
                        .HasFilter("[Status] = N'Active'");

                    b.ToTable("Loan", "circulation");
                });

            modelBuilder.Entity("LibraryManagement.Shared.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DeadOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateTimeOffset>("StoredOn")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_OutboxMessage_Pending")
                        .HasFilter("[ProcessedOn] IS NULL AND [DeadOn] IS NULL");

                    b.ToTable("OutboxMessage", "circulation");
                });

            modelBuilder.Entity("LibraryManagement.Circulation.Domain.Holds.HoldQueue", b =>
                {
                    b.OwnsMany("LibraryManagement.Circulation.Domain.Holds.Hold", "Holds", b1 =>
                        {
                            b1.Property<Guid>("EditionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("BorrowerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("ExpiryWarningSent")
                                .HasColumnType("bit");

                            b1.Property<DateOnly?>("PickupDeadline")
                                .HasColumnType("date");

                            b1.Property<DateTimeOffset>("PlacedOn")
                                .HasColumnType("datetimeoffset");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("nvarchar(16)");

                            b1.Property<Guid?>("TrappedCopyId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("EditionId", "Id");

                            b1.HasIndex("BorrowerId");

                            b1.HasIndex("TrappedCopyId")
                                .IsUnique()
                                .HasFilter("[TrappedCopyId] IS NOT NULL");

                            b1.ToTable("Hold", "circulation");

                            b1.WithOwner()
                                .HasForeignKey("EditionId");
                        });

                    b.Navigation("Holds");
                });

            modelBuilder.Entity("LibraryManagement.Circulation.Domain.Loans.Loan", b =>
                {
                    b.OwnsMany("LibraryManagement.Circulation.Domain.Loans.Reminder", "RemindersSent", b1 =>
                        {
                            b1.Property<Guid>("LoanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("DaysFromDue")
                                .HasColumnType("int")
                                .HasColumnName("DaysFromDue");

                            b1.HasKey("LoanId", "DaysFromDue");

                            b1.ToTable("LoanReminderSent", "circulation");

                            b1.WithOwner()
                                .HasForeignKey("LoanId");
                        });

                    b.Navigation("RemindersSent");
                });
#pragma warning restore 612, 618
        }
    }
}
