<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>LibraryManagement.Shared.Application</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Mediator.Abstractions" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\LibraryManagement.Shared.Domain\LibraryManagement.Shared.Domain.csproj" />
    </ItemGroup>

</Project>
